# Introduction à Numpy

Python ne contient pas de structure permettant de traiter des données numériques efficacement. Pour un usage scientifique il est utile d'avoir une structure de type tableau dans lequel <b>l'ensemble des données sont du même type</b>, et dont <b>la taille n'est pas modifiable</b>. C'est le cas des tableaux créés via le module NUMPY. Pour importer ce module, on tape par exemple

In [1]:
# Importer tout numpy sous le nom (plus court) np 
import numpy as np
# On peut aussi faire "from numpy import *" 
# qui fera l'économie du np.

Numpy inclut les fonctions d'autres modules comme par exemple le <b>module math</b>.

In [2]:
# calcul d'un cosinus
np.cos(2*np.pi/3)

-0.4999999999999998

## Les tableaux multidimensionnels numpy

On crée un tableau grâce à l'instruction `array`  qui prend comme argument une liste Python pour un vecteur 1D ou bien des listes imbriquées pour une matrice de dimensions quelconques.

In [4]:
# Les lignes sont données entre crochets, 
# séparées par des virgules comme suit :
a = np.array([ [1.5,3.14,5.27], [2.17,0.69,1.414] ])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[ 1.5    3.14   5.27 ]
 [ 2.17   0.69   1.414]]


In [ ]:
print(a)

### Attributs

In [5]:
# Les dimensions du tableaux
a.shape

(2, 3)

In [6]:
# Le type des données
print(a.dtype)

float64


<b>Note :</b> lors de la création du tableau on aurait pu choisir le type de donnée avec l'argument optionnel <b>dtype = int, float, complex, bool</b>.

On peut même définir exactement le nombre de bits sur lequel coder ces données avec
<b>dtype = int64, int16, float128, complex128</b>

In [7]:
#Le nombre de dimensions
a.ndim

2

In [8]:
# Le nombre d'éléments
a.size

6

Et d'autres...

### Générer un tableau grâce aux fonctions de `numpy`

Nous avons vu comment créer un tableau à partir d'une liste. Il existe des fonctions qui permettent de créer certains tableaux.

#### Tableau 1D avec `arange`

In [9]:
# La fonction `arange(start, stop, step)` fonctionne
# comme la fonction `range` de Python
np.arange(-1, 1, 0.3)

array([-1. , -0.7, -0.4, -0.1,  0.2,  0.5,  0.8])

#### Tableau 1D avec `linspace(start, stop, npoints)` et `logspace(start, stop, npoints)`

`linspace(start, stop, npoints)` permet comme `arange` de créer un tableau d'éléments régulièrement espacés mais en spécifiant le nombre d'éléments plutôt que le pas. `logspace` fonctionne de la même manière mais génère une échelle logarithmique. <b>Notez que les points de départ et d'arrivée sont inclus.</b>

In [10]:
# Exemple de linspace
np.linspace(0, 10, 12)

array([  0.        ,   0.90909091,   1.81818182,   2.72727273,
         3.63636364,   4.54545455,   5.45454545,   6.36363636,
         7.27272727,   8.18181818,   9.09090909,  10.        ])

In [11]:
# Exemple de logspace de base 10
#(pour un logarithme népérien, il faudrait mettre "base=np.e")
np.logspace(0, 10, 12, base=10)

array([  1.00000000e+00,   8.11130831e+00,   6.57933225e+01,
         5.33669923e+02,   4.32876128e+03,   3.51119173e+04,
         2.84803587e+05,   2.31012970e+06,   1.87381742e+07,
         1.51991108e+08,   1.23284674e+09,   1.00000000e+10])

#### Matrice diagonale

In [12]:
# Une matrice diagonale
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### Matrices de zéros et de 1

In [13]:
# Attention aux parenthèses supplémentaires
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [14]:
# Attention aux parenthèses supplémentaires
np.ones((2, 2))

array([[ 1.,  1.],
       [ 1.,  1.]])

Et bien d'autres...

## Opération élément par élément

Un grand nombre d'opérations simples peuvent être réalisées sur des tableaux.

In [15]:
# Exemple d'opération terme à terme
a = np.array([[1.5,3.14,5.27],[2.17,0.69,1.414]])
b = 2*a + a**2 - a
print(b)

[[  3.75      12.9996    33.0429  ]
 [  6.8789     1.1661     3.413396]]


Notez que si l'on faisait la même chose avec une liste cela prendrait beaucoup plus de temps.

In [16]:
# Calcul des N premiers carrés à l'aide d'une liste
a = [i**2 for i in range(2000000)]

In [17]:
# Calcul des N premiers carrés à l'aide d'un tableau numpy
b = np.arange(2000000)**2

Pour utiliser les fonctions de base (<i>cosinus, sinus, exponentielle,</i> etc...), il ne faut pas utiliser le module math, mais les fonctions incluses dans numpy qui fonctionnent avec les tableaux.

In [18]:
# Prendre l'exponentielle terme à terme d'un tableau
a = np.linspace(0,1, num=10)
print(np.exp(-a**2/2))

[ 1.          0.99384617  0.97561098  0.94595947  0.90595519  0.85699689
  0.8007374   0.7389913   0.67363846  0.60653066]


## Vectoriser une fonction

Si l'on a écrit une fonction prenant en argument un entier ou un nombre à virgule flottante, on peut la transformer en une fonction accetant un tableau numpy grâce à l'instruction `vectorize`.

In [3]:
# Fonction qui calcule l'exponentielle d'un nombre
def exponentielle(x):
    epsilon = 1E-6
    resultat = 0.
    n = 1.
    terme = 1. # Valeur initiale du terme de la boucle
    while terme>epsilon :
        resultat = resultat + terme
        terme = terme * x/n
        n = n+1
    return resultat

La fonction exponentielle n'accepte que des nombres, pas des tableaux. Pour la transformer en une fonction qui accepte les tableaux, sans modifier la fonction, on utilise `vectorize`.

In [4]:
# On crée un tableau numpy auquel on veut appliquer ma_fonction
vecx = np.linspace(0,1,100)
print(exponentielle(2))
exponentielle(vecx)
# Appliquer la fonction à un tableau numpy n'est pas possible.

7.389055882389215


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [28]:
# On vectorize la fonction puis on l'applique à vecx
exponentielle = np.vectorize(exponentielle)
exponentielle(vecx)

array([ 1.        ,  1.01015203,  1.02040746,  1.0307668 ,  1.04123128,
        1.0518019 ,  1.06247971,  1.07326677,  1.08416278,  1.09516939,
        1.10628773,  1.11751892,  1.12886412,  1.14032446,  1.15190112,
        1.16359525,  1.17540804,  1.18734194,  1.19939605,  1.21157254,
        1.22387264,  1.2362976 ,  1.2488487 ,  1.2615272 ,  1.27433441,
        1.28727163,  1.30034017,  1.31354136,  1.32687655,  1.3403471 ,
        1.35395544,  1.36770106,  1.38158621,  1.39561233,  1.40978084,
        1.42409319,  1.43855083,  1.45315525,  1.46790793,  1.48281037,
        1.4978641 ,  1.51307064,  1.52843156,  1.54394841,  1.55962278,
        1.57545626,  1.59145047,  1.60760812,  1.62392886,  1.64041529,
        1.6570691 ,  1.67389197,  1.69088563,  1.70805181,  1.72539227,
        1.74290876,  1.76060308,  1.77847703,  1.79653243,  1.81477113,
        1.83319499,  1.85180589,  1.87060571,  1.88959639,  1.90877986,
        1.92815807,  1.947733  ,  1.96750773,  1.98748225,  2.00

# Manipuler les tableaux

### Tableau 1D

#### Manipulation par les indices

La manipulation par indices est très similaire aux listes. Réferrez-vous donc au cours sur les listes.

In [ ]:
# Création d'un tableau 1D avec linspace
a = np.linspace(0, 1, 20)
# Affichage des termes d'indices pairs
print(a[::2])

#### Indexation par un tableau booléen

Très utile pour sélectionner certains éléments d'un tableau vérifiants une certaine condition.

In [29]:
a = np.linspace(0, 1, 20)
# Création d'un tableau booléen
# de même taille que `a` contenant 
# True si l'élémént est >=0.5, False sinon
cond = a>=0.5
print(a)
print(cond)

[ 0.          0.05263158  0.10526316  0.15789474  0.21052632  0.26315789
  0.31578947  0.36842105  0.42105263  0.47368421  0.52631579  0.57894737
  0.63157895  0.68421053  0.73684211  0.78947368  0.84210526  0.89473684
  0.94736842  1.        ]
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True]


In [30]:
# Extraction des éléments de `a` qui
# vérifient la condition (être >= 0.5)
# grâce à l'indexation par un tableau 
# de booléens
b = a[cond]
print(b)

[ 0.52631579  0.57894737  0.63157895  0.68421053  0.73684211  0.78947368
  0.84210526  0.89473684  0.94736842  1.        ]


De manière plus compacte :

In [31]:
a = np.linspace(0, 1, 20)
# On ne garde dans a que les éléments 
# supérieurs ou égaux à 5
a = a[a>0.5]
print(a)

[ 0.52631579  0.57894737  0.63157895  0.68421053  0.73684211  0.78947368
  0.84210526  0.89473684  0.94736842  1.        ]


### Tableaux 2D

#### Extraction de lignes/colonnes

In [32]:
a = np.array([[1,2], [1,9]])
print(a)
print(a[:, 0]) # Colonne d'indice 0
print(a[1, :]) # Ligne d'indice 1

[[1 2]
 [1 9]]
[1 1]
[1 9]


#### Algèbre matricielle

Le produit matriciel est la fonction `dot()`

In [33]:
a = np.array([[1,2], [1,9]])
b = np.array([[3, 1.],[3.14, 6.02]])
c = np.dot(a, b)
print(c)

[[  9.28  13.04]
 [ 31.26  55.18]]


Le sous module de Numpy appelé `linalg` (linear algebra) permet de faire tout un tas de choses : valeurs propres, vecteurs propres, inversion de matrice, déterminant ...

In [34]:
# Valeurs propres et vecteurs propores
print(np.linalg.eig(c))

(array([  1.66314049,  62.79685951]), array([[-0.86348499, -0.23673526],
       [ 0.50437453, -0.9715742 ]]))


### Méthodes des tableaux Numpy

Tansposition, produit matriciel, conjugaison, transconjugaison, minimum, maximum, moyenne, somme etc... Un exemple important :

#### Changer la frome d'un tableau : `reshape`

Permet de changer la forme d'un tableau sans en changer la taille (le nombre d'éléments).

In [35]:
a = np.arange(10)
print(a)
print(a.reshape((5, 2)))
a

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Note : attention ici la methode ne modifie pas le tableau a. 

#### Aller voir les fonctions `tile`, `concatenate`, `vstack`, `hstack`...

### Parcourir un tableau

On parcourt un tableau avec des boucles `for` comme pour les autres structures de données. En particulier on peut utiliser `enumerate`.

### Lecture et écriture dans un fichier

#### Format ASCII : `savetxt` et `loadtxt`

On peu lire/enregistrer un fichier texte contenant un tableau grâce à `savetxt(fileID, tableau)` et `loadtxt`. On peut spécifier les séparateurs de lignes et colonnes. Utiliser un fichier ASCII dans le cas de très gros fichiers, peut s'avérer peu opportun car très lent. Dans ce cas on préfèrera sauver en binaire.

#### Format Binaire : `load` et `save`

Plus rapide et sans erreurs d'arrondi possible qu'en ASCII, mais illisible par des logiciels tels que Excel, Word, ou n'importe quel éditeur de texte.

### Copie d'un tableau

Lorsque l'on assigne un tableau à un autre tableau, Python ne copie pas le tableau, seulement la référence.

In [36]:
# Exemple de passage de référence
a = np.array([[1, 2],[3, 4]])
# On associe b au même tableau a
b = a

In [37]:
# Modification d'un élément de a
a[1, 1] = 78675

In [38]:
# B aussi est modifié
print(b)

[[    1     2]
 [    3 78675]]


Pour forcer la copie d'un tableau (deep copy en anglais) il faut utiliser l'instruction `copy`

In [ ]:
# Exemple de deep copy de a
c = np.copy(a)
a[0, 0] = 122343
print(c)

# Introduction à Scipy

Scipy est un package qui contient toutes les fonctions utiles au scientifique. <b>Scipy inclut Numpy.</b> La documentation des fonctions se trouve <a href = "http://docs.scipy.org/doc/scipy/reference/">ici</a>.
    
* Fonctions spéciales 
* Intégration
* Optimisation
* Interpolation
* Transformation de Fourier
* Traitement du signal
* Algèbre linéaire
* Matrices "clairesemée" (sparse)
* Statistique
* Traitement d'images
* Ecriture dans fichiers
    

In [39]:
import scipy as sc

In [40]:
# Scipy inclut Numpy
a = sc.array([1, 2])

In [41]:
# Scipy inclut les fonctions spéciales
from scipy import special as spe
# Comme la fonction erf()
spe.erf(a)

array([ 0.84270079,  0.99532227])